# general settings
name: my_train
model_type: HATModel
scale: 2
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/projects/HAT-main-dip/datasets/DIV2K/DIV2K_train_HR_sub
    dataroot_lq: /root/autodl-tmp/projects/HAT-main-dip/datasets/DIV2K/DIV2K_train_LR_bicubic/X2_sub
    #meta_info_file: hat/data/meta_info/meta_info_DF2Ksub_GT.txt
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /root/autodl-tmp/projects/HAT-main-dip/datasets/Set5/GTmod12
    dataroot_lq: /root/autodl-tmp/projects/HAT-main-dip/datasets/Set5/LRbicx2
    io_backend:
      type: disk

#  val_2:
#    name: Set14
#    type: PairedImageDataset
#    dataroot_gt: /root/autodl-tmp/projects/HAT-main-dip/datasets/Set5/GTmod12
#    dataroot_lq: /root/autodl-tmp/projects/HAT-main-dip/datasets/Set5/LRbicx2
#    io_backend:
#      type: disk

  # val_3:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: /root/autodl-tmp/projects/HAT-main-dip/datasets/urban100/GTmod12
  #   dataroot_lq: /root/autodl-tmp/projects/HAT-main-dip/datasets/urban100/LRbicx2
  #   io_backend:
  #     type: disk


# network structures
network_g:
  type: HAT
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
#  pretrain_network_g: ~
  pretrain_network_g: ./experiments/pretrained_models/HAT_SRx2_ImageNet-pretrain.pth
  strict_load_g: true
  param_key_g: 'params_ema'

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

#  perceptual_opt:
#    type: PerceptualLoss
#    layer_weights:
#      conv1_1: 1.0
#      conv2_1: 1.0
#      conv3_1: 1.0
#      conv4_1: 1.0
#      conv5_1: 1.0

val:
  val_freq: !!float 500
  save_img: True
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
